### ISSUE TITLE
Failed build in Andorid

### ISSUE THREAD

**Issue by AricWu** [joltup/rn-fetch-blob#235]
When I build a new react native project ,
and do the steps: 

1. `npm install --save rn-fetch-blob`
2. `RNFB_ANDROID_PERMISSIONS=true react-native link`

And run in android studio.
I got these erros:
```
Error:(9, 34) package android.support.v4.content not exist
Error:(12, 33) package com.facebook.react.bridge not exist
...
```
The error file is `.../node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlob.java`

![image](https://user-images.githubusercontent.com/30997051/48615876-079b8400-e9cd-11e8-8c2f-dbc49897a8a9.png)

My package.json is 
```
"dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "rn-fetch-blob": "^0.10.13"
  },
```
Andorid Studio Version:3.0.1

**Comment by JofBigHealth** [comment]
@AricWu From memory RN 0.57.x requires Android Studio 3.1.x

**Comment by erbud** [comment]
Hi,

I reproduce the same incidence with:

"dependencies": {
     "react": "16.3.1",
     "react-native": "0.55.4",
     "rn-fetch-blob": "^ 0.10.15"
   },

And Android Studio 3.3

Should I upgrade to RN 0.57.x? I understand that RNFB 0.10.15 is compatible with RN 0.55, I say good?

Regards,

**Comment by JofBigHealth** [comment]
@erbud RN doesn't support Android 3.3. Just 3.1.x as of 0.57. I've not checked the docs for 0.58 and 0.59 (pre-release) but I'm almost certain that will be true also. So downgrade Android Studio to 3.1.4 and see if it still works.

Also, you're missing out on a lot of great stuff being on 0.55.x. I know RN upgrading can be a lot of effort but if you can spare a few hours you'll gain a lot from 0.58. Especially if you do a lot of Android work.

**Comment by erbud** [comment]
@JofBigHealth with Android Studio 3.1.4 I reproduce the same incidence that with Android Studio 3.3. I'm disoriented…

![image](https://user-images.githubusercontent.com/3479770/52009958-81271680-24d4-11e9-89d9-daa5f389d617.png)

**Comment by erbud** [comment]
@JofBigHealth Yes, it is an app ejected and use ExpoKit. In fact I have ejected it because the Expo API limits me when I want to download a file and open it after.  It seems that with RNFB it is feasible, but I can't achieve integrate it correctly.

By the way, thank you very much for the time dedicated to help me.

**Comment by JofBigHealth** [comment]
@erbud No problem. Ok, I don't want to clog up this issue's comments further.... If I get time over the weekend I'll try out your test case and report back. No promises though. You'll probably have more success via Twitter, Discord or similar than me but I'll do what I can. Might be an issue with the lib so worth investigating.

**Comment by erbud** [comment]
@JofBigHealth I'm not a big Android connoisseur, but I think I have the JAR library "com.android.support-v4" incomplete.

I will try to complete the installation. Let's see if I have lucky...

<img width="1344" alt="com android support-support-v4" src="https://user-images.githubusercontent.com/3479770/52073070-e1769080-2586-11e9-8dd3-a534279bbdc2.png">

**Comment by JofBigHealth** [comment]
@erbud Hi, sorry I haven't had chance to do this. Can you remember why specifically you ejected Expo? Reason I ask is I may build and release our own fetch blob lib so I'd like to best understand the features needed.

**Comment by erbud** [comment]
@JofBigHealth In the development in which I participate I need to download files (pdf, doc, etc.) and, once downloaded, open them.

So far I used the **Expo 30.x SDK (RN 0.55.4)**. With the FileSystem API I correctly download the files but, when opening them, with the Linking API, you don't have access/permissions to open them (Linking.openURL('file://...')).

Then I got to know the project <rn-fetch-blob> and I decided to try it. I made an Expo eject, solved all the problems and left the development stable. I installed <rn-fetch-blob> and that is when I came across the problem that I mention in this thread.

I felt stuck, I decided to undo Expo eject and install **Expo SDK 32.x (RN 0.57.1)**, since I read in the change log:

> FileSystem: Allow access to more external directories. (Related PRs: 1, 2.)
> 
> (1) https://github.com/expo/expo/pull/2748
> (2) https://github.com/expo/expo/pull/2808

And now I'm on it, struggling to configure correctly the Intent filters.

```
// app.json

{
  "expo": {
    …
    "android": {
      …
      "intentFilters": [
        {
          "action": "VIEW",
          "data": {
            "scheme": "file",
            "mimeType": "*/*",
            "pathPattern": ".*\\.pdf",
            "host": "*",
          },
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
    }
  }
}
```
Let's see if I can get it ...

**Comment by Developer-Deep** [comment]
@erbud Were you able to solve Linking with expo? I'm stuck at the same issue for weeks now and I don't wanna eject.

**Comment by GolfSkiWorld** [comment]
Me too.
I ejected my project from expo.
but I can't build my app after link rn-fetch-blob.
I hope to fix this issue asap.

**Comment by erbud** [comment]
Hi bros.,

The best solution I have found is:

```
import { WebView } from 'expo';

class MyComponent extends React.Component {
    
    _fileSelected =(url = 'http://…') => {
        this.setState({
            fileViewerVisibility: true,
            fileUrl: url
        });
    };

    render() {
        return (
            <Modal transparent={true} visible={this.state.fileViewerVisibility}>
                <WebView source={{uri: this.state.fileUrl}} />
            </Modal>
        );
    };

}
```

If there is no connection but the file has been previously opened it is also opened since it is cached.

If there is no connection and the file has not been opened before, there is a Warning that must be controlled.

I also tried to open the files directly with the associated application on the device (`Linking.openUrl ('http: // ...');`), once open they are also cached and can be accessed without connection; but I had a problem with the focus of the applications, the first time I opened some of the applications associated with the files, the apps stayed in the background and I did not know how to control it.

I hope you can use my experience.

Regards,

**Comment by erbud** [comment]
Another solution: `WebBrowser.openBrowserAsync(url);`

**Comment by Developer-Deep** [comment]
Thank you @erbud, will try it!

**Comment by lylest** [comment]
the same problem using  android studio 3.4
