### ISSUE TITLE
Crash when using 0.10.16 on react-native 0.59.10

### ISSUE THREAD

**Issue by rynvva** [joltup/rn-fetch-blob#403]
I know 0.10.16 is intended to support 0.60.0 react-native, but that version makes app terminating when running app from ```react-native run-android``` in 0.59.10 react-native

**Comment by yakisama12** [comment]
@renalpraba Can you post any exception details? 🤔

**Comment by geisterfurz007** [comment]
I guess 0.10.16 is not intended to be used with react-native below 0.60.0. RN0.60 changed from the android support libraries to using androidx; you can see some of the changes in [this commit](https://github.com/joltup/rn-fetch-blob/commit/e83f84f1329218c3cf52b99d7a0dbb3a1a8c47d8). Considering that you are running 0.59.10, you very likely didn't change the gradle files to get that working and you shouldn't if you plan on staying on 0.59.10.

You can go through the list of commits since 0.10.15 [here](https://github.com/joltup/rn-fetch-blob/compare/v0.10.15...master) and see if there is anything that changes any functionality and use [patch-package](https://www.npmjs.com/package/patch-package) to safe the changes in your project.   Given that the release is for supporting 0.60.0 though, I assume that there is no new stuff introduced.

**Comment by Ladekarl** [comment]
I just ran into this as well. 
This should probably at least be a minor version bump since it is breaking for any React Native version below 0.60.

**Comment by Traviskn** [comment]
if you are not yet upgraded to react native 0.60 or higher, rn-fetch-blob 0.10.16 will not work for you, you'll have to stay on 0.10.15.  Unfortunately with this library being a pre-1.0 release you should assume just about every change is breaking. I'll look into revising how we handle version numbers going forward though to reduce this problem

**Comment by renalpraba** [comment]
I should have been said it straight, if it a breaking change why it's not documented

**Comment by renalpraba** [comment]
yes @Traviskn better version numbers and more clear information about compatible version on the readme 👍

**Comment by khanh10101998** [comment]
I have the same error, does anyone have a solution ?.  I run on android and crash :((

**Comment by Traviskn** [comment]
the readme has been updated: 

```rn-fetch-blob version 0.10.16 is only compatible with react native 0.60 and up. It should have been a major version bump, we apologize for the mistake. If you are not yet upgraded to react native 0.60 or above, you should remain on rn-fetch-blob version 0.10.15```

**Comment by adisr1804** [comment]
rn-fetch-blob v.0.10.16 not compatible to RN <0.60, I was updated my RN to 0.60 and just to normally run. first time I shock when I'm updating the package and making break of my code. Lol 💃 

try this : 
react-native upgrade or react-native init [New Build & New Version 0.60.3]

**Comment by DanielLe232** [comment]
I have this same issue
My solution is just install version we need.
react-native --save rn-fetch-blob@0.10.13{version we need}

If wanna latest version we need upgrade latest version react-native

**Comment by adisr1804** [comment]
First, you must be delete the node_modules & package-lock.json and you can see your dependency rn-fetch-blob "^0.10.16" and then you can change to "0.10.15", and you npm install or sudo install (Mac), it's work in react-native <0.60

**Comment by rezareact** [comment]
I have this same problem. I just install 0.10.15 and that's ok.
react-native 0.59.9,
rn-fetch-blob 0.10.15

**Comment by 841660202** [comment]
1、$ yarn remove rn-fetch-blob
2、in package.json, change `"rn-fetch-blob": "^0.10.15" `to `"rn-fetch-blob": "0.10.15"`
3、$ yarn
