### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by laurent22** [joltup/rn-fetch-blob#51]
The project was taken from @wkh237 over two months ago but to be honest it seems as inactive as the parent project - no response on issues, no new commits, no merged pull requests.

Are there any plans to actually improve the project?

**Comment by tombailey** [comment]
@Traviskn I would be willing to help out with some of the issues and PRs here if you can grant me collaborator access?

**Comment by Traviskn** [comment]
@laurent22 We've actually [merged 3 pull requests](https://github.com/joltup/react-native-fetch-blob/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged), but I understand that this fork probably hasn't had as much activity everyone expected.  

One challenge we've run into is publishing on npm, as we cannot access the original `react-native-fetch-blob` npm account.  We're considering either publishing under the `@joltup` namespace or moving to a new repo with a new name entirely.

The other challenge is becoming familiar enough with the codebase to be smart about merging pull requests, and giving good feedback on pull requests.

This library has been very stable in our products at work and we have not run into any pressing issues, so that is why we have had trouble prioritizing time to dedicate to the project.  I do want to try and do better at responding to community issues and PRs though.

@tombailey We'd love to have community help with issues and PR's!  If you can answer questions in open issues that would be awesome.  For getting collaborator access to be able to merge PRs, would you mind emailing me? travis.nuttall at joltup.com

**Comment by emusgrave** [comment]
Should the readme be updated to reflect that this fork is not what is in npm?

**Comment by Traviskn** [comment]
We've just finished re-naming the project for npm, and published a new release with updates/bugfixes/etc.  Thanks for your patience 😃
