### ISSUE TITLE
Could not update the podfile because of missing authors field in the podspec

### ISSUE THREAD

**Issue by yll090** [joltup/rn-fetch-blob#86]
As the title suggests.

* please provide the version of installed library and RN project. -- 0.10.10
* a sample code snippet/repository is very helpful to spotting the problem. -- Install the library/update from the master. Currently I cannot update the pods because there is a missing authors field (deleted most likely mistakenly in this [commit](https://github.com/joltup/rn-fetch-blob/commit/5721cb7396368cbe4e1dabc2ab9a5d842535ba21))

**Comment by Traviskn** [comment]
Thanks for reporting this, I should have realized that field is required

**Comment by yll090** [comment]
Nothing to worry about, mate. Thanks for the timely reaction. :)

**Comment by mountHouli** [comment]
Hi! I am also having this issue. I'm sorry to bug you and not contribute anything, but...
1. Do you know when this fix will be implemented?
2. Is there a workaround/hotfix I can apply to my code?  (Unfortunately any change I make to node_modules/rn-fetch-blob/rn-fetch-blob.podspec will get lost because I have node_modules .gitignored)

**Comment by mountHouli** [comment]
Never mind my questions #1 and #2 from above.
3. Do you know when the next version/tag will be released, so that in my `package.json` dependencies can grab the repo from npm rather than what I'm doing now which is `"rn-fetch-blob": "git://github.com/joltup/rn-fetch-blob#master"` ?

Sorry to bother you :-/ . Many thanks!

**Comment by Traviskn** [comment]
@mountHouli I've just published an updated version, 0.10.11 that should fix the broken podspec 😃

**Comment by mountHouli** [comment]
Many thanks!
